### ISSUE TITLE
`cross_val_predict` from sklearn gives an interesting error for the entity extractor

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/NLU-engine-prototype-benchmarks#1]
All the relevant information can be found in this [notebook](https://github.com/secretsauceai/NLU-engine-prototype-benchmarks/blob/main/BUG_entity_general_domain_cross_val.ipynb) to reproduce and document the error.

**Comment by AmateurAcademic** [comment]
This was a funny one. It seems in the `general` domain (scenario), there aren't enough tagged entities to train a model. The error wasn't so helpful to determine this:
```
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for further details.

Canceled future for execute_request message before replies were done
```

To fix this, I added the following into `get_entity_reports_for_domains`:
```
def check_percent_of_non_entities(domain_df):
        number_of_nan_entities = domain_df['entity_types'].isnull().sum()
        total_size = len(domain_df)
        percent_no_entities = number_of_nan_entities / total_size
        return percent_no_entities

    for domain in domains:
        print(f'Evaluating entity classifier for {domain}')
        domain_df = data_df[data_df['scenario'] == domain]


        percent_of_non_entities = check_percent_of_non_entities(domain_df)

        if percent_of_non_entities > 0.90:
            print(
                f'{domain} has {percent_of_non_entities}% non-entities. It is too sparse to evaluate.'
                )
            continue
```

I''m not sure if this is the right amount needed. It may also depend on the size of the data set. But this quick fix works for now. If anyone ever gets this error, this is the reason and the `percent_of_non_entities` threshold will have to be changed.
