### ISSUE TITLE
Find a good separation criteria for entity refinement

### ISSUE THREAD

**Issue by secretsauceai** [secretsauceai/NLU-engine-prototype-benchmarks#2]
The [refactored notebook for entity refinement](https://github.com/secretsauceai/NLU-engine-prototype-benchmarks/blob/main/Macro_NLU_Entity_refinement_refactored.ipynb) (work in progress) needs a good way to separate the entries to be refined. 

Currently, if we separate the errors by domain (scenario/skill) the top one (calendar) will have 681 errors. This is far too many for a user to be expected to review in one go using ipysheet. I am uncertain if they should be separated by intent is the case with intent refinement. 

This needs to be solved to facility the entity refinement to achieve the deliverable of the data set.

**Comment by AmateurAcademic** [comment]
Fix the bug from [cross_val_predict from sklearn gives an interesting error for the entity extractor](https://github.com/secretsauceai/NLU-engine-prototype-benchmarks/issues/1), created a graph for domain level scoring from the results. This is good to have an overview. For the refinement within a domain, the entity types by percent correct will be used, then all incorrect (where the `answer_annotation` column doesn't match the 'predicted_tagging' column) entities that have been tagged will be reviewed by type for each domain.
